// <auto-generated />
namespace Oauthdemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class newcoloumnadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcoloumnadd));
        
        string IMigrationMetadata.Id
        {
            get { return "202102171849473_newcoloumnadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
