//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoFieldDb.Api_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imagestore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imagestore()
        {
            this.Products = new HashSet<Product>();
            this.services = new HashSet<service>();
            this.Sub_Category = new HashSet<Sub_Category>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Isalive { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string photourl { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> SubcateogoryId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> serviceId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Category> Sub_Category { get; set; }
    }
}
