//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoFieldDb.Api_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SEOKeyword { get; set; }
        public string SEOUrl { get; set; }
        public Nullable<bool> IsAlive { get; set; }
        public Nullable<System.DateTime> createon { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
        public string skucode { get; set; }
        public string itemcode { get; set; }
        public string brandname { get; set; }
        public string features { get; set; }
        public Nullable<bool> stockstaus { get; set; }
        public Nullable<long> stockquantity { get; set; }
        public Nullable<long> minquantity { get; set; }
        public Nullable<decimal> price_mrp { get; set; }
        public Nullable<bool> price_mrp_display { get; set; }
        public Nullable<bool> showonhome { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<long> ImageId { get; set; }
        public string SEOTitle { get; set; }
        public Nullable<long> serviceId { get; set; }
        public string couponid { get; set; }
    
        public virtual Imagestore Imagestore { get; set; }
    }
}
